#pragma once

enum ErrorCodes {
    WRONG_RANGE = 1,
    CANNOT_OPEN_IMAGE = 2,
    IMAGE_CHANNELS_NOT_SUPPORTED = 3,
    DATA_SIZE_NOT_EQUAL = 4,
    UNEXPECTED_EOF = 5,
    WRONG_NUMBER_OF_PARAMETERS = 6,
    WRONG_FIRST_PARAMETER = 7,
    FILE_DOES_NOT_EXIST = 8,
    UNRECOGNIZED_MODE = 9,
    WRONG_DISTRIBUTION_TYPE = 10,
    WRONG_TYPE_OF_GENERATION = 11
};